name: AOS Release

on: [push]

jobs:
  apk:
      name: Generate APK
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v1
        - name: set up JDK 17
          uses: actions/setup-java@v1
          with:
            java-version: 17
        - name: Build debug APK
          run: bash ./gradlew assembleDebug --stacktrace
          working-directory: ./do-android
        - name: Upload APK
          uses: actions/upload-artifact@v1
          with:
            name: app
            path: do-android/app/build/outputs/apk/debug
        - name: upload artefact to App Center
          uses: wzieba/AppCenter-Github-Action@v1
          with:
            appName: mooooong/do
            token: ${{secrets.APP_CENTER_TOKEN}}
            group: Collaborators
            file: do-android/app/build/outputs/apk/debug/app-debug.apk
            notifyTesters: true
            debug: false
