# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - humanbackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./do-backend

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Generate Environment Variables File for Production
        run: |
          echo "PORT=$PORT" >> .env
          echo "APP_HOST=$APP_HOST" >> .env
          echo "DB_CONNECTION=$DB_CONNECTION" >> .env
          echo "DB_HOST=$DB_HOST" >> .env
          echo "DB_PORT=$DB_PORT" >> .env
          echo "DB_USERNAME=$DB_USERNAME" >> .env
          echo "DB_PASSWORD=$DB_PASSWORD" >> .env
          echo "DB_DATABASE=$DB_DATABASE" >> .env
          echo "DB_SYNCHRONIZED=$DB_SYNCHRONIZED" >> .env
          echo "DB_LOGGING=$DB_LOGGING" >> .env
          echo "DB_ENTITIES=$DB_ENTITIES" >> .env
        env:
          PORT: ${{ secrets.PORT }}
          APP_HOST: ${{ secrets.APP_HOST }}
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_SYNCHRONIZED: ${{ secrets.DB_SYNCHRONIZED }}
          DB_LOGGING: ${{ secrets.DB_LOGGING }}
          DB_ENTITIES: ${{ secrets.DB_ENTITIES }}

      - name: npm install, build
        run: |
          npm install --legacy-peer-deps
          npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: node-app.zip
        run: |
          zip -r node-app.zip .
        working-directory: ./do-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
        run: |
          unzip node-app.zip
          rm node-app.zip

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "humanbackend"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_081F540FA71445C49EBBC06921DFFAC5 }}
          package: .
